Update static.yml

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -244,19 +244,19 @@ jobs:
         run: az afd endpoint purge --resource-group azusctr-rg --profile-name azusctr-cdn --endpoint-name ${{ env.cdn_endpoint }} --domains ${{ env.cdn_domain }} --content-paths '/*'
 
       - name: Set Azure Static Web Apps Token
-         run:|
-           if [[ "${{ github.event.inputs.environment }}" == "tru-uat" ]]; then
-             echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_UAT }}" >> $GITHUB_ENV
-           elif [[ "${{ github.event.inputs.environment }}" == "tru-uat-auto" ]]; then
-             echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_UAT_AUTO }}" >> $GITHUB_ENV
-            else
-              echo "Environment is not or is unrecognized."
-              exit 1
-           fi
+        run: |
+          if [[ "${{ github.event.inputs.environment }}" == "tru-uat" ]]; then
+            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_UAT }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event.inputs.environment }}" == "tru-uat-auto" ]]; then
+            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_UAT_AUTO }}" >> $GITHUB_ENV
+          else
+            echo "Error: Unrecognized environment - ${{ github.event.inputs.environment }}"
+            exit 1
+          fi
 
       - name: Webapp Deploy
         id: webapp_deploy
-        if: ${{ vars.ENVIRONMENT == 'uat' || vars.ENVIRONMENT == 'tru-prod'  || vars.ENVIRONMENT == 'prod' }}
+        if: ${{ vars.ENVIRONMENT == 'uat' || vars.ENVIRONMENT == 'tru-prod' || vars.ENVIRONMENT == 'prod' }}
         uses: Azure/static-web-apps-deploy@v1
         with:
           azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
@@ -267,6 +267,7 @@ jobs:
           app_location: "dist"
           output_location: ""
           is_static_export: true
+
           
       # Azure logout
       - name: logout
